[package]
name = "wgpu_one"
version = "0.1.0"
authors = ["fredlangva <fredlangva@gmail.com>"]
edition = "2018"

[features]
default = []
dx12 = ["wgpu/dx12"]

[dependencies]
wgpu = "0.2.3"
glsl-to-spirv = "*"
arcball = "*"
cgmath = "*"
tobj = "*"
